import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _locale = const Locale('en');
  
  Locale get locale => _locale;
  bool get isArabic => _locale.languageCode == 'ar';

  LanguageProvider() {
    _loadLocale();
  }

  void _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString('language_code') ?? 'en';
    _locale = Locale(langCode);
    notifyListeners();
  }

  void toggleLanguage() async {
    if (_locale.languageCode == 'en') {
      _locale = const Locale('ar');
    } else {
      _locale = const Locale('en');
    }
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', _locale.languageCode);
    notifyListeners();
  }

  String translate(String key) {
    if (isArabic) {
      return _arabic[key] ?? key;
    }
    return _english[key] ?? key;
  }

  static const Map<String, String> _english = {
    'dashboard': 'Dashboard',
    'users': 'Users',
    'projects': 'Projects',
    'reports': 'Reports',
    'logout': 'Logout',
    'manage_projects': 'Manage Projects',
    'view_manage_projects': 'View and manage all system projects.',
    'project_details_admin': 'Project Details (Admin)',
    'owner': 'Owner',
    'status': 'Status',
    'created_at': 'Created At',
    'participants': 'Participants',
    'tasks': 'Tasks',
    'description': 'Description',
    'delete_project_system': 'Delete Project from System',
    'sections_and_tasks': 'Sections and Tasks',
    'no_sections_found': 'No sections or tasks found for this project yet.',
    'report_details': 'Report Details',
    'system_reports': 'System Reports',
    'view_manage_reports': 'View and manage user-submitted reports for projects and accounts.',
    'reported_target': 'Reported Target',
    'reporter': 'Reporter',
    'project_manager': 'Project Manager',
    'reason': 'Reason',
    'dismiss_report': 'Dismiss Report',
    'take_action_delete': 'Take Action (Delete)',
    'approve_report': 'Approve Report',
    'reject_report': 'Reject Report',
    'cancel': 'Cancel',
    'confirm_delete': 'Confirm Delete',
    'project_deleted_success': 'Project deleted successfully',
    'delete_confirm_msg': 'Are you sure you want to delete this project permanently? This action cannot be undone.',
    'report_about': 'Report about',
    'no_reports_available': 'No reports currently available.',
    'search_resources': 'Search resources...',
    'system_overview': 'System Overview',
    'real_time_metrics': 'Real-time performance metrics and recent administrative activity.',
    'total_projects': 'TOTAL PROJECTS',
    'total_users': 'TOTAL USERS',
    'recent_projects': 'Recent Projects',
    'view_all': 'View All',
    'new_users': 'New Users',
    'server_status': 'Server Status',
    'online': 'Online',
    'edit_profile': 'Edit Profile',
    'account_overview': 'Account Overview',
    'account_settings': 'Account Settings',
    'manage_admin_profile': 'Manage your administrative profile and preferences.',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'last_login': 'Last Login',
    'change_password': 'Change Password',
    'export_data': 'Export Data',
    'members': 'members',
    'tasks_count': 'tasks',
    'no_tasks': 'No tasks in this section.',
    'no_description': 'No description available.',
    'manage_users': 'Manage Users',
    'view_manage_users': 'View and manage all system users.',
    'id': 'ID',
    'name': 'Name',
    'email': 'Email',
    'role': 'Role',
    'actions': 'Actions',
    'confirm_approve_report': 'Are you sure you want to approve this report? The reported content will be deleted.',
    'confirm_dismiss_report': 'Are you sure you want to dismiss this report?',
    'add_note_optional': 'Add a note for the user (optional)...',
    'confirm_and_delete': 'Confirm and Delete',
    'dismiss': 'Dismiss',
    'report_date': 'Report Date',
    'error_loading_projects': 'Error loading projects',
    'failed_to_delete_project': 'Failed to delete project',
    'error_loading_users': 'Error loading users',
    'failed_to_delete_user': 'Failed to delete user',
    'error_loading_reports': 'Error loading reports',
    'failed_to_delete_report': 'Failed to delete report',
    
    // User Dashboard Screen
    'welcome_back': 'Welcome back',
    'welcome_sub_prefix': 'You have ',
    'projects_stat': ' project',
    'projects_stat_plural': ' projects',
    'tasks_stat': ' task',
    'tasks_stat_plural': ' tasks',
    'and': ' and ',
    'my_projects': 'My Projects',
    'join_via_link': 'Join via Link',
    'explore_public_projects': 'Explore Public Projects',
    'my_tasks': 'My Tasks',
    'no_projects_yet': 'No projects yet',
    'create_first_project_started': 'Create your first project to get started!',
    'start_new_project': 'Start New Project',
    'need_help_invite_team': 'Need help? Invite your team',
    'no_tasks_yet': 'No tasks yet',
    'tasks_appear_join_projects': 'Tasks will appear here when you join projects.',
    'join_via_invite_title': 'Join via Invite Link',
    'paste_invite_code': 'Paste the invite link or code you received:',
    'paste_invite_placeholder': 'Paste invite link or code...',
    'invalid_invite_code': 'Invalid or expired invite link',
    'view_project': 'View Project',
    'loading_btn': 'Loading...',
    'public': 'Public',
    'private': 'Private',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'todo': 'To Do',
    'done': 'Done',
    
    // Projects & Joined Projects Screens
    'explore_public': 'Explore Public',
    'filter': 'Filter',
    'sort': 'Sort',
    'here_are_projects': 'Here are your projects',
    'projects_joined_title': 'Projects you have joined',
    'no_joined_projects': 'No joined projects yet',
    'projects_joined_sub': 'Projects you join will appear here!',
    'member_since_today': 'Member since: Today',
    'created_at_label': 'Created at: ',
    'skills_required': 'Skills:',
    'team_members': 'Team Members:',
    'tasks_count_stat': 'TASKS',
    'team_count_stat': 'TEAM',
    'deadline_stat': 'DEADLINE',
    'today': 'Today',
    
    // Help Center Screen
    'how_can_help': 'How can we help?',
    'search_help_placeholder': 'Search for articles, guides, or keywords...',
    'browse_by_category': 'BROWSE BY CATEGORY',
    'getting_started': 'Getting Started',
    'getting_started_sub': 'New to Nexus? Learn the basics and set up your first workspace in minutes.',
    'explore_guide': 'EXPLORE GUIDE',
    'project_management': 'Project Management',
    'project_management_sub': 'Master task tracking, milestones, and advanced team collaboration tools.',
    'view_articles': 'VIEW ARTICLES',
    'troubleshooting': 'Troubleshooting',
    'troubleshooting_sub': 'Encountering an issue? Find solutions for common technical questions and bugs.',
    'get_support': 'GET SUPPORT',
    'popular_resources': 'Popular Resources',
    'view_all_docs': 'View all documentation',
    'resource_workflows': 'Setting up automated workflows',
    'resource_reports': 'Exporting project reports (PDF/CSV)',
    'resource_invite': 'Inviting external collaborators',
    'resource_perms': 'Managing team permissions',
    'still_need_help': 'Still need help?',
    'support_available_247': 'Our support team is available 24/7 to assist you.',
    'start_live_chat': 'Start a Live Chat',

    // Profile & Edit Profile Screens
    'profile_title': 'Profile',
    'edit_profile_title': 'Edit Profile',
    'bio_label': 'Bio',
    'skills_label': 'Skills',
    'assigned_tasks': 'Assigned Tasks',
    'completed_tasks_profile': 'Completed Tasks',
    'general_info': 'General Information',
    'save_profile': 'Save Profile',
    'skills_list_title': 'Skills List',
    'add_skill_placeholder': 'Add a skill and press Enter',
    'profile_updated_success': 'Profile updated successfully!',
    'failed_update_profile': 'Failed to update profile.',
    'help_center': 'Help Center',
    'biography': 'Biography',
    'no_skills_added': 'No skills added yet',
    'active': 'Active',
    'finished': 'Finished',
    'points_suffix': ' pts',
    'progress_label': 'Progress',
    'change_profile_photo': 'Change Profile Photo',
    'full_name': 'Full Name',
    'username_label': 'Username',
    'please_enter': 'Please enter ',
    'save_profile_warning': 'Make sure all your information is correct before saving.',
    'save_changes': 'Save Changes',
  };

  static const Map<String, String> _arabic = {
    'dashboard': 'لوحة التحكم',
    'users': 'المستخدمين',
    'projects': 'المشاريع',
    'reports': 'البلاغات',
    'logout': 'تسجيل الخروج',
    'manage_projects': 'إدارة المشاريع',
    'view_manage_projects': 'استعرض وقم بإدارة كافة مشاريع النظام.',
    'project_details_admin': 'تفاصيل المشروع (أدمن)',
    'owner': 'المالك',
    'status': 'الحالة',
    'created_at': 'تاريخ الإنشاء',
    'participants': 'المشاركين',
    'tasks': 'المهام',
    'description': 'الوصف',
    'delete_project_system': 'حذف المشروع من النظام',
    'sections_and_tasks': 'الأقسام والمهام',
    'no_sections_found': 'لا توجد أقسام أو مهام في هذا المشروع حتى الآن.',
    'report_details': 'تفاصيل البلاغ',
    'system_reports': 'بلاغات النظام',
    'view_manage_reports': 'مراجعة البلاغات المقدمة من المستخدمين واتخاذ الإجراءات اللازمة.',
    'reported_target': 'الهدف المبلّغ عنه',
    'reporter': 'مقدم البلاغ',
    'project_manager': 'مدير المشروع',
    'reason': 'السبب',
    'dismiss_report': 'تجاهل البلاغ',
    'take_action_delete': 'اتخاذ إجراء (حذف)',
    'approve_report': 'قبول البلاغ',
    'reject_report': 'رفض البلاغ',
    'cancel': 'إلغاء',
    'confirm_delete': 'تأكيد الحذف',
    'project_deleted_success': 'تم حذف المشروع بنجاح',
    'delete_confirm_msg': 'هل أنت متأكد من رغبتك في حذف هذا المشروع نهائياً؟ لا يمكن التراجع عن هذا الإجراء.',
    'report_about': 'بلاغ عن',
    'no_reports_available': 'لا توجد بلاغات حالياً.',
    'search_resources': 'البحث عن موارد...',
    'system_overview': 'نظرة عامة على النظام',
    'real_time_metrics': 'مقاييس الأداء في الوقت الفعلي والنشاط الإداري الأخير.',
    'total_projects': 'إجمالي المشاريع',
    'total_users': 'إجمالي المستخدمين',
    'recent_projects': 'المشاريع الأخيرة',
    'view_all': 'عرض الكل',
    'new_users': 'المستخدمين الجدد',
    'server_status': 'حالة السيرفر',
    'online': 'متصل',
    'edit_profile': 'تعديل الملف الشخصي',
    'account_overview': 'نظرة عامة على الحساب',
    'account_settings': 'إعدادات الحساب',
    'manage_admin_profile': 'إدارة ملفك الشخصي الإداري وتفضيلاتك.',
    'email_address': 'عنوان البريد الإلكتروني',
    'phone_number': 'رقم الهاتف',
    'last_login': 'آخر تسجيل دخول',
    'change_password': 'تغيير كلمة المرور',
    'export_data': 'تصدير البيانات',
    'members': 'أعضاء',
    'tasks_count': 'مهام',
    'no_tasks': 'لا توجد مهام في هذا القسم.',
    'no_description': 'لا يوجد وصف متاح.',
    'manage_users': 'إدارة المستخدمين',
    'view_manage_users': 'استعرض وقم بإدارة كافة مستخدمي النظام.',
    'id': 'المعرف',
    'name': 'الاسم',
    'email': 'البريد الإلكتروني',
    'role': 'الدور',
    'actions': 'الإجراءات',
    'confirm_approve_report': 'هل أنت متأكد من قبول البلاغ؟ سيتم حذف المحتوى المبلغ عنه.',
    'confirm_dismiss_report': 'هل أنت متأكد من تجاهل هذا البلاغ؟',
    'add_note_optional': 'أضف ملاحظة للمستخدم (اختياري)...',
    'confirm_and_delete': 'تأكيد وحذف',
    'dismiss': 'تجاهل',
    'report_date': 'تاريخ البلاغ',
    'error_loading_projects': 'خطأ في تحميل المشاريع',
    'failed_to_delete_project': 'فشل حذف المشروع',
    'error_loading_users': 'خطأ في تحميل المستخدمين',
    'failed_to_delete_user': 'فشل حذف المستخدم',
    'error_loading_reports': 'خطأ في تحميل البلاغات',
    'failed_to_delete_report': 'فشل حذف البلاغ',
    
    // User Dashboard Screen
    'welcome_back': 'مرحباً بك مجدداً',
    'welcome_sub_prefix': 'لديك ',
    'projects_stat': ' مشروع',
    'projects_stat_plural': ' مشاريع',
    'tasks_stat': ' مهمة',
    'tasks_stat_plural': ' مهام',
    'and': ' و ',
    'my_projects': 'مشاريعي الخاصة',
    'join_via_link': 'الانضمام عبر رابط',
    'explore_public_projects': 'استكشاف المشاريع العامة',
    'my_tasks': 'مهامي النشطة',
    'no_projects_yet': 'لا توجد مشاريع حتى الآن',
    'create_first_project_started': 'قم بإنشاء مشروعك الأول للبدء بالعمل!',
    'start_new_project': 'بدء مشروع جديد',
    'need_help_invite_team': 'بحاجة لمساعدة؟ ادعُ فريقك الآن',
    'no_tasks_yet': 'لا توجد مهام حالياً',
    'tasks_appear_join_projects': 'ستظهر المهام هنا عند انضمامك إلى المشاريع وإسناد المهام إليك.',
    'join_via_invite_title': 'الانضمام عبر رابط دعوة',
    'paste_invite_code': 'الصق رابط الدعوة أو رمز المشروع الذي تلقيته:',
    'paste_invite_placeholder': 'الصق رابط الدعوة أو الرمز هنا...',
    'invalid_invite_code': 'رابط الدعوة أو رمز المشروع غير صالح أو منتهي الصلاحية',
    'view_project': 'عرض تفاصيل المشروع',
    'loading_btn': 'جاري التحميل...',
    'public': 'عام',
    'private': 'خاص',
    'completed': 'مكتمل',
    'in_progress': 'قيد التنفيذ',
    'todo': 'للإنجاز',
    'done': 'مكتمل',
    
    // Projects & Joined Projects Screens
    'explore_public': 'استكشاف المشاريع العامة',
    'filter': 'تصفية',
    'sort': 'ترتيب حسب',
    'here_are_projects': 'إليك مشاريعك الحالية في النظام',
    'projects_joined_title': 'المشاريع التي انضممت إليها',
    'no_joined_projects': 'لم تنضم إلى أي مشاريع حتى الآن',
    'projects_joined_sub': 'المشاريع العامة أو الخاصة التي تنضم إليها ستظهر هنا!',
    'member_since_today': 'عضو منذ: اليوم',
    'created_at_label': 'تم الإنشاء في: ',
    'skills_required': 'المهارات المطلوبة:',
    'team_members': 'أعضاء الفريق:',
    'tasks_count_stat': 'المهام',
    'team_count_stat': 'أعضاء الفريق',
    'deadline_stat': 'الموعد النهائي',
    'today': 'اليوم',
    
    // Help Center Screen
    'how_can_help': 'كيف يمكننا مساعدتك؟',
    'search_help_placeholder': 'البحث عن مقالات، أدلة إرشادية، أو كلمات مفتاحية...',
    'browse_by_category': 'تصفح حسب الفئات الرئيسية',
    'getting_started': 'البدء والاستخدام الأول',
    'getting_started_sub': 'هل أنت جديد في النظام؟ تعلم أساسيات تهيئة مساحة عملك وإدارة المشاريع في دقائق.',
    'explore_guide': 'استكشف الدليل الكامل',
    'project_management': 'إدارة المشاريع والتعاون',
    'project_management_sub': 'أتقن تتبع وإسناد المهام، وإدارة المعالم الرئيسية، وأدوات العمل الجماعي المتقدمة.',
    'view_articles': 'عرض المقالات المتاحة',
    'troubleshooting': 'حل المشكلات والأعطال',
    'troubleshooting_sub': 'هل واجهتك مشكلة تقنية؟ اعثر على إجابات للأسئلة الشائعة والحلول الفنية السريعة.',
    'get_support': 'طلب الدعم الفني المباشر',
    'popular_resources': 'الموارد والوثائق الأكثر شيوعاً',
    'view_all_docs': 'عرض كافة وثائق الدعم الفني',
    'resource_workflows': 'إعداد مسارات العمل وسير العمل المؤتمت',
    'resource_reports': 'تصدير تقارير المشاريع والإنتاجية (PDF/CSV)',
    'resource_invite': 'دعوة المتعاونين والشركاء الخارجيين للمشاريع',
    'resource_perms': 'إدارة وتعيين صلاحيات وأدوار أعضاء الفريق',
    'still_need_help': 'هل ما زلت بحاجة إلى مساعدة إضافية؟',
    'support_available_247': 'فريق الدعم الفني متواجد لمساعدتك على مدار الساعة 24/7.',
    'start_live_chat': 'بدء محادثة مباشرة الآن',

    // Profile & Edit Profile Screens
    'profile_title': 'الملف الشخصي',
    'edit_profile_title': 'تعديل الملف الشخصي',
    'bio_label': 'نبذة شخصية (Bio)',
    'skills_label': 'المهارات والخبرات',
    'assigned_tasks': 'المهام الخاصة المسندة',
    'completed_tasks_profile': 'المهام التي تم إكمالها',
    'general_info': 'المعلومات الشخصية العامة',
    'save_profile': 'حفظ التعديلات والملف الشخصي',
    'skills_list_title': 'قائمة المهارات الشخصية',
    'add_skill_placeholder': 'اكتب المهارة هنا واضغط Enter للإضافة',
    'profile_updated_success': 'تم تحديث ملفك الشخصي بنجاح!',
    'failed_update_profile': 'فشل في تحديث بيانات الملف الشخصي.',
    'help_center': 'مركز المساعدة',
    'biography': 'النبذة الشخصية',
    'no_skills_added': 'لم يتم إضافة أي مهارات بعد',
    'active': 'نشطة',
    'finished': 'مكتملة',
    'points_suffix': ' نقطة',
    'progress_label': 'التقدم',
    'change_profile_photo': 'تغيير الصورة الشخصية',
    'full_name': 'الاسم الكامل',
    'username_label': 'اسم المستخدم',
    'please_enter': 'الرجاء إدخال ',
    'save_profile_warning': 'تأكد من صحة معلوماتك الشخصية قبل حفظ الملف.',
    'save_changes': 'حفظ التغييرات',
  };
}

